aws_region          = "eu-west-1"
project_name        = "BuildItAll"
data_bucket_name    = "builditall-client-data"
airflow_bucket_name = "builditall-airflow"
logs_bucket_name    = "builditall-logs"