name: CD
on:
  push:
    branches: [main]

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}        
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./infrastructure
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infrastructure

  deploy-terraform:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate-terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 
      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: ./infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  Upload-to-S3:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'    
    needs: deploy-terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload setup.sh to S3
        run: |
          aws s3 cp orchestration/setup.sh s3://builditall-airflow/setup.sh
      - name: Upload start-airflow.sh to S3
        run: |
          aws s3 cp orchestration/start-airflow.sh s3://builditall-airflow/start-airflow.sh
      - name: Upload docker-compose.yml to S3
        run: |
          aws s3 cp orchestration/docker-compose.yml s3://builditall-airflow/docker-compose.yml
      - name: Upload Dockerfile to S3
        run: |
          aws s3 cp orchestration/Dockerfile s3://builditall-airflow/Dockerfile
      - name: Upload Dag requirements.txt to S3
        run: |
          aws s3 cp orchestration/requirements.txt s3://builditall-airflow/requirements/requirements.txt
      - name: Upload Dags to S3
        run: |
          aws s3 cp orchestration/dags/ s3://builditall-airflow/dags/ --recursive
      - name: Upload Spark Jobs to S3 
        run: |
          aws s3 cp spark_jobs/ s3://builditall-client-data/scripts/ --recursive          